show_on:
  default: discovery
  type: enum
  choices:
    - discovery
    - homepage
    - all
  description: discovery refers to topic list pages

muted_category:
  default: 'Events'
  type: 'list'

svg_icons:
  default: 'sort-amount-up|comments'
  type: 'list'
  list_type: 'compact'